spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
      password: root
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    main:
      allow-bean-definition-overriding: true
    profiles:
      active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl


